version: '3.8'   

services:

  backend:
    build: ./backend   # Build backend image from backend folder
    container_name: backend_app
    ports:
      - "5000:5000"   # Map port 5000 (host:container)
    depends_on:
      - mongo          # Backend waits for MongoDB

  frontend:
    build: ./frontend  # Build frontend image
    container_name: frontend_app
    ports:
      - "3000:80"     # Nginx runs on port 80 inside container
    depends_on:
      - backend

  mongo:
    image: mongo       # Pull official MongoDB image
    container_name: mongo_db
    ports:
      - "27017:27017"
